### ISSUE TITLE
fresh man wan to know  package --'unfoldNd'

### ISSUE THREAD

**Issue by haomosthandsome** [FirasBDarwish/ConvKAN3D#7]
I am fresh in python , can you tell me how to install the package 'unfoldNd'.I search all package in conda ,but not see it .Thank you very much bro.

**Comment by FirasBDarwish** [comment]
Hello! Thanks for checking out the repo.

conda is a package and environment manager and you would typically use it to create, manage, and switch between isolated environments containing different versions of Python and packages.

What you need to use is pip, the default package manager for Python that allows you to download packages from PyPi (which is where 'unfoldNd' is).

Just a heads up: if you'd like to use the ConvKAN3D package, all you need to do is:
`pip install ConvKAN3D` in the command line of whatever development environment you're using.

It will automatically take care of installing all required packages and dependencies, like 'unfoldNd'.

If you're asking about using unfoldNd for your own use, all you need to do is
`pip install unfoldNd`.
I've linked the GitHub repo for unfoldNd [here](https://github.com/f-dangel/unfoldNd), it can help you in case you run into any issues during the installation. :) 

Best,
Firas
